# Generated by Django 4.2.25 on 2025-10-11 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('address_1', models.CharField(max_length=128, verbose_name='Address')),
                ('address_2', models.CharField(blank=True, max_length=128, verbose_name='Address continue')),
                ('city', models.CharField(default='Tacoma', max_length=64, verbose_name='City')),
                ('state', localflavor.us.models.USStateField(default='WA', max_length=2, verbose_name='State')),
                ('zip_code', models.CharField(default='98490', max_length=5, verbose_name='zip code')),
                ('is_insured', models.BooleanField(default=False, verbose_name='Has insurance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
