# Generated by Django 4.2.25 on 2025-10-11 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='f_name',
            field=models.CharField(max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='l_name',
            field=models.CharField(max_length=100, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='m_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Middle name'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='prefix',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mister'), ('Dr.', 'Doctor'), ('Ms.', 'Miss'), ('Mrs.', 'Missus')], max_length=4, verbose_name='Prefix'),
        ),
    ]
